services:
  cart:
    build:
      context: .
      dockerfile: cart/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mart-system
    depends_on:
      - products
      - loms

  loms:
    build:
      context: .
      dockerfile: loms/Dockerfile
    ports:
      - "8083:8083"
      - "8084:8084"
    networks:
      - mart-system
    depends_on:
      postgres-replica:
        condition: service_healthy
      kafka-init-topics:
        condition: service_completed_successfully

  notifier:
    build:
      context: .
      dockerfile: notifier/Dockerfile
    networks:
      - mart-system
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully

  products:
    image: gitlab-registry.ozon.dev/go/classroom-20/students/homework-draft/products:latest
    ports:
      - "8082:8082"
    networks:
      - mart-system
  
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    ports:
      - "8100:8080"
    networks:
      - mart-system
    environment:
      SWAGGER_JSON: /swagger/swagger.json
    volumes:
      - ./loms/api/openapiv2/loms.swagger.json:/swagger/swagger.json

  postgres-master:
    image: gitlab-registry.ozon.dev/go/classroom-20/students/base/postgres:16
    container_name: postgres-master
    environment:
      - POSTGRESQL_USERNAME=loms-user
      - POSTGRESQL_PASSWORD=loms-password
      - POSTGRESQL_DATABASE=loms_db
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
    ports:
      - "5432:5432"
    networks:
      - mart-system

  postgres-replica:
    image: gitlab-registry.ozon.dev/go/classroom-20/students/base/postgres:16
    container_name: postgres-replica
    depends_on:
      - postgres-master
    environment:
      - POSTGRESQL_USERNAME=loms-user
      - POSTGRESQL_PASSWORD=loms-password
      - POSTGRESQL_DATABASE=loms_db
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgres-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    ports:
      - "5433:5432"
    networks:
      - mart-system
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loms-user -d loms_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  comments:
    build:
      context: .
      dockerfile: comments/Dockerfile
    ports:
      - "8085:8085"
      - "8086:8086"
    networks:
      - mart-system
    depends_on:
      postgres-comments-shard-1:
        condition: service_healthy
      postgres-comments-shard-2:
        condition: service_healthy

  postgres-comments-shard-1:
    image: gitlab-registry.ozon.dev/go/classroom-20/students/base/postgres:16
    environment:
      - POSTGRESQL_USERNAME=comments-user-1
      - POSTGRESQL_PASSWORD=comments-password-1
      - POSTGRESQL_DATABASE=comments_db
    ports:
      - "5434:5432"
    networks:
      - mart-system
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comments-user-1 -d comments_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres-comments-shard-2:
    image: gitlab-registry.ozon.dev/go/classroom-20/students/base/postgres:16
    environment:
      - POSTGRESQL_USERNAME=comments-user-2
      - POSTGRESQL_PASSWORD=comments-password-2
      - POSTGRESQL_DATABASE=comments_db
    ports:
      - "5435:5432"
    networks:
      - mart-system
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comments-user-2 -d comments_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka-init-topics:
    container_name: kafka-init-topics
    image: confluentinc/cp-kafka:7.7.1.arm64
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
      cub kafka-ready -b kafka0:29092 1 90 && \
      kafka-topics --create --topic loms.order-events --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka0:29092'"
    networks:
      - mart-system

networks:
  mart-system:
    driver: bridge
