services:
  cart:
    build:
      context: .
      dockerfile: cart/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - products
      - loms

  loms:
    build:
      context: .
      dockerfile: loms/Dockerfile
    ports:
      - "8083:8083"
      - "8084:8084"
    depends_on:
      postgres-replica:
        condition: service_healthy

  products:
    image: gitlab-registry.ozon.dev/go/classroom-20/students/homework-draft/products:latest
    ports:
      - "8082:8082"
  
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    ports:
      - "8100:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.json
    volumes:
      - ./loms/api/openapiv2/loms.swagger.json:/swagger/swagger.json

  postgres-master:
    image: gitlab-registry.ozon.dev/go/classroom-20/students/base/postgres:16
    container_name: postgres-master
    environment:
      - POSTGRESQL_USERNAME=loms-user
      - POSTGRESQL_PASSWORD=loms-password
      - POSTGRESQL_DATABASE=loms_db
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
    ports:
      - "5432:5432"

  postgres-replica:
    image: gitlab-registry.ozon.dev/go/classroom-20/students/base/postgres:16
    container_name: postgres-replica
    depends_on:
      - postgres-master
    environment:
      - POSTGRESQL_USERNAME=loms-user
      - POSTGRESQL_PASSWORD=loms-password
      - POSTGRESQL_DATABASE=loms_db
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgres-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loms-user -d loms_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
