bin-deps:
	GOBIN=$(LOCAL_BIN) go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1 && \
	GOBIN=$(LOCAL_BIN) go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0 && \
	GOBIN=$(LOCAL_BIN) go install github.com/envoyproxy/protoc-gen-validate@v1.0.4 && \
	GOBIN=$(LOCAL_BIN) go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.19.1


bin-deps-win:
	set "GOBIN=$(LOCAL_BIN)" && \
	go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1 && \
	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2.0 && \
	go install github.com/envoyproxy/protoc-gen-validate@v1.0.4 && \
	go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.19.1

vendor-rm:
	rm -rf vendor-proto

vendor-rm-win:
	if exist vendor-proto rmdir /s /q vendor-proto


vendor-proto/google/protobuf-common:
	git clone -b main --single-branch -n --depth=1 --filter=tree:0 \
		https://github.com/protocolbuffers/protobuf vendor-proto/protobuf &&\
	cd vendor-proto/protobuf &&\
	git sparse-checkout set --no-cone src/google/protobuf &&\
	git checkout

vendor-proto/google/protobuf: vendor-proto/google/protobuf-common
	mkdir -p vendor-proto/google
	mv vendor-proto/protobuf/src/google/protobuf vendor-proto/google
	rm -rf vendor-proto/protobuf

vendor-proto/google/protobuf-win: vendor-proto/google/protobuf-common
	if not exist vendor-proto\google mkdir vendor-proto\google
	if exist vendor-proto\protobuf\src\google\protobuf move vendor-proto\protobuf\src\google\protobuf vendor-proto\google
	if exist vendor-proto\protobuf rmdir /s /q vendor-proto\protobuf


vendor-proto/validate-common:
	git clone -b main --single-branch --depth=2 --filter=tree:0 \
	https://github.com/bufbuild/protoc-gen-validate vendor-proto/tmp && \
	cd vendor-proto/tmp && \
	git sparse-checkout set --no-cone validate &&\
	git checkout

vendor-proto/validate: vendor-proto/validate-common
	mkdir -p vendor-proto/validate
	mv vendor-proto/tmp/validate vendor-proto
	rm -rf vendor-proto/tmp

vendor-proto/validate-win: vendor-proto/validate-common
	if exist vendor-proto\tmp\validate move vendor-proto\tmp\validate vendor-proto
	if exist vendor-proto\tmp rmdir /s /q vendor-proto\tmp


vendor-proto/google/api-common:
	git clone -b master --single-branch -n --depth=1 --filter=tree:0 \
 		https://github.com/googleapis/googleapis vendor-proto/googleapis && \
 	cd vendor-proto/googleapis && \
	git sparse-checkout set --no-cone google/api && \
	git checkout

vendor-proto/google/api: vendor-proto/google/api-common
	mkdir -p  vendor-proto/google
	mv vendor-proto/googleapis/google/api vendor-proto/google
	rm -rf vendor-proto/googleapis

vendor-proto/google/api-win: vendor-proto/google/api-common
	if exist vendor-proto\googleapis\google\api move vendor-proto\googleapis\google\api vendor-proto\google
	if exist vendor-proto\googleapis rmdir /s /q vendor-proto\googleapis


vendor-proto: vendor-rm vendor-proto/google/protobuf vendor-proto/validate vendor-proto/google/api
vendor-proto-win: vendor-rm-win vendor-proto/google/protobuf-win vendor-proto/validate-win vendor-proto/google/api-win


protoc-generate:
	mkdir -p pkg/api/comments/v1
	protoc \
	-I ${PROTO_FILES_PATH} \
	-I vendor-proto \
	--plugin=protoc-gen-go=$(LOCAL_BIN)/protoc-gen-go \
	--go_out pkg/api \
	--go_opt paths=source_relative \
	--plugin=protoc-gen-go-grpc=$(LOCAL_BIN)/protoc-gen-go-grpc \
	--go-grpc_out pkg/api \
	--go-grpc_opt paths=source_relative \
	--plugin=protoc-gen-validate=$(LOCAL_BIN)/protoc-gen-validate \
    --validate_out="lang=go,paths=source_relative:pkg/api" \
	--plugin=protoc-gen-grpc-gateway=$(LOCAL_BIN)/protoc-gen-grpc-gateway \
    --grpc-gateway_out pkg/api \
    --grpc-gateway_opt logtostderr=true  \
	--grpc-gateway_opt paths=source_relative \
	--grpc-gateway_opt generate_unbound_methods=true \
	api/comments/v1/comments.proto && \
	go mod tidy

protoc-generate-win:
	if not exist pkg\api\comments\v1 mkdir pkg\api\comments\v1
	protoc \
	-I ${PROTO_FILES_PATH} \
	-I vendor-proto \
	--plugin=protoc-gen-go=$(LOCAL_BIN)/protoc-gen-go.exe \
	--go_out pkg/api \
	--go_opt paths=source_relative \
	--plugin=protoc-gen-go-grpc=$(LOCAL_BIN)/protoc-gen-go-grpc.exe \
	--go-grpc_out pkg/api \
	--go-grpc_opt paths=source_relative \
	--plugin=protoc-gen-validate=$(LOCAL_BIN)/protoc-gen-validate.exe \
    --validate_out="lang=go,paths=source_relative:pkg/api" \
	--plugin=protoc-gen-grpc-gateway=$(LOCAL_BIN)/protoc-gen-grpc-gateway.exe \
    --grpc-gateway_out pkg/api \
    --grpc-gateway_opt logtostderr=true  \
	--grpc-gateway_opt paths=source_relative \
	--grpc-gateway_opt generate_unbound_methods=true \
	api/comments/v1/comments.proto && \
	go mod tidy