service:
  host: localhost
  port: 8080
  workers: 5
  graceful_shutdown_timeout: 10
  tracing:
    service_name: cart-service
    environment: ci

repo_observer:
  interval: 5
  
jaeger:
  host: localhost
  port: 6831

product_service:
  protocol: http
  host: product-service
  port: 8082
  token: testToken
  limit: 10
  burst: 10

loms_service:
  host: localhost
  port: 8083
