service:
  host: localhost
  grpc_port: 8083
  http_port: 8084
  grpc_gateway:
    read_header_timeout: 10
    write_timeout: 15
    idle_timeout: 60
  graceful_shutdown_timeout: 10
  tracing:
    service_name: loms-service
    environment: development

jaeger:
  host: jaeger
  port: 4318

db_master:
  host: postgres-master
  port: 5432
  user: loms-user
  password: loms-password
  db_name: loms_db

db_replica:
  host: postgres-replica
  port: 5432
  user: loms-user
  password: loms-password
  db_name: loms_db

kafka:
  host: localhost
  port: 29092
  order_topic: loms.order-events
  brokers: localhost:9092
