service:
  host: localhost
  grpc_port: 8083
  http_port: 8084
  grpc_gateway:
    read_header_timeout: 10
    write_timeout: 15
    idle_timeout: 60
  load_stocks_data_timeout: 10
  gracefull_shutdown_timeout: 10

jaeger:
  host: localhost
  port: 6831

db_master:
  host: postgres-master
  port: 5432
  user: loms-user
  password: loms-password
  db_name: loms_db

db_replica:
  host: postgres-replica
  port: 5432
  user: loms-user
  password: loms-password
  db_name: loms_db

kafka:
  host: kafka
  port: 29092
  order_topic: loms.order-events
  brokers: kafka:29092
