service:
  host: localhost
  grpc_port: 8083
  http_port: 8084
  grpc_gateway:
    read_header_timeout: 10s
    write_timeout: 15s
    idle_timeout: 60s
  graceful_shutdown_timeout: 10s
  tracing:
    service_name: loms-service
    environment: ci

jaeger:
  host: localhost
  port: 6831

db_master:
  host: postgres-master
  port: 5432
  user: loms-user
  password: loms-password
  db_name: loms_db

db_replica:
  host: postgres-replica
  port: 5432
  user: loms-user
  password: loms-password
  db_name: loms_db

kafka:
  host: kafka
  port: 29092
  order_topic: loms.order-events
  brokers: kafka:29092

order_outbox_publisher:
  batch_size: 10
  period_seconds: 1
