// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i route256/loms/internal/service.OrderRepository -o order_repository_mock.go -n OrderRepositoryMock -p mocks

import (
	"context"
	"route256/loms/internal/domain"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// OrderRepositoryMock implements mm_service.OrderRepository
type OrderRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetByID          func(ctx context.Context, orderID int64) (op1 *domain.Order, err error)
	funcGetByIDOrigin    string
	inspectFuncGetByID   func(ctx context.Context, orderID int64)
	afterGetByIDCounter  uint64
	beforeGetByIDCounter uint64
	GetByIDMock          mOrderRepositoryMockGetByID

	funcInsert          func(ctx context.Context, order *domain.Order) (i1 int64, err error)
	funcInsertOrigin    string
	inspectFuncInsert   func(ctx context.Context, order *domain.Order)
	afterInsertCounter  uint64
	beforeInsertCounter uint64
	InsertMock          mOrderRepositoryMockInsert

	funcUpdateStatus          func(ctx context.Context, orderID int64, newStatus domain.Status) (err error)
	funcUpdateStatusOrigin    string
	inspectFuncUpdateStatus   func(ctx context.Context, orderID int64, newStatus domain.Status)
	afterUpdateStatusCounter  uint64
	beforeUpdateStatusCounter uint64
	UpdateStatusMock          mOrderRepositoryMockUpdateStatus
}

// NewOrderRepositoryMock returns a mock for mm_service.OrderRepository
func NewOrderRepositoryMock(t minimock.Tester) *OrderRepositoryMock {
	m := &OrderRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetByIDMock = mOrderRepositoryMockGetByID{mock: m}
	m.GetByIDMock.callArgs = []*OrderRepositoryMockGetByIDParams{}

	m.InsertMock = mOrderRepositoryMockInsert{mock: m}
	m.InsertMock.callArgs = []*OrderRepositoryMockInsertParams{}

	m.UpdateStatusMock = mOrderRepositoryMockUpdateStatus{mock: m}
	m.UpdateStatusMock.callArgs = []*OrderRepositoryMockUpdateStatusParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOrderRepositoryMockGetByID struct {
	optional           bool
	mock               *OrderRepositoryMock
	defaultExpectation *OrderRepositoryMockGetByIDExpectation
	expectations       []*OrderRepositoryMockGetByIDExpectation

	callArgs []*OrderRepositoryMockGetByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OrderRepositoryMockGetByIDExpectation specifies expectation struct of the OrderRepository.GetByID
type OrderRepositoryMockGetByIDExpectation struct {
	mock               *OrderRepositoryMock
	params             *OrderRepositoryMockGetByIDParams
	paramPtrs          *OrderRepositoryMockGetByIDParamPtrs
	expectationOrigins OrderRepositoryMockGetByIDExpectationOrigins
	results            *OrderRepositoryMockGetByIDResults
	returnOrigin       string
	Counter            uint64
}

// OrderRepositoryMockGetByIDParams contains parameters of the OrderRepository.GetByID
type OrderRepositoryMockGetByIDParams struct {
	ctx     context.Context
	orderID int64
}

// OrderRepositoryMockGetByIDParamPtrs contains pointers to parameters of the OrderRepository.GetByID
type OrderRepositoryMockGetByIDParamPtrs struct {
	ctx     *context.Context
	orderID *int64
}

// OrderRepositoryMockGetByIDResults contains results of the OrderRepository.GetByID
type OrderRepositoryMockGetByIDResults struct {
	op1 *domain.Order
	err error
}

// OrderRepositoryMockGetByIDOrigins contains origins of expectations of the OrderRepository.GetByID
type OrderRepositoryMockGetByIDExpectationOrigins struct {
	origin        string
	originCtx     string
	originOrderID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByID *mOrderRepositoryMockGetByID) Optional() *mOrderRepositoryMockGetByID {
	mmGetByID.optional = true
	return mmGetByID
}

// Expect sets up expected params for OrderRepository.GetByID
func (mmGetByID *mOrderRepositoryMockGetByID) Expect(ctx context.Context, orderID int64) *mOrderRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("OrderRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &OrderRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.paramPtrs != nil {
		mmGetByID.mock.t.Fatalf("OrderRepositoryMock.GetByID mock is already set by ExpectParams functions")
	}

	mmGetByID.defaultExpectation.params = &OrderRepositoryMockGetByIDParams{ctx, orderID}
	mmGetByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByID.expectations {
		if minimock.Equal(e.params, mmGetByID.defaultExpectation.params) {
			mmGetByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByID.defaultExpectation.params)
		}
	}

	return mmGetByID
}

// ExpectCtxParam1 sets up expected param ctx for OrderRepository.GetByID
func (mmGetByID *mOrderRepositoryMockGetByID) ExpectCtxParam1(ctx context.Context) *mOrderRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("OrderRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &OrderRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("OrderRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &OrderRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByID
}

// ExpectOrderIDParam2 sets up expected param orderID for OrderRepository.GetByID
func (mmGetByID *mOrderRepositoryMockGetByID) ExpectOrderIDParam2(orderID int64) *mOrderRepositoryMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("OrderRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &OrderRepositoryMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("OrderRepositoryMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &OrderRepositoryMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.orderID = &orderID
	mmGetByID.defaultExpectation.expectationOrigins.originOrderID = minimock.CallerInfo(1)

	return mmGetByID
}

// Inspect accepts an inspector function that has same arguments as the OrderRepository.GetByID
func (mmGetByID *mOrderRepositoryMockGetByID) Inspect(f func(ctx context.Context, orderID int64)) *mOrderRepositoryMockGetByID {
	if mmGetByID.mock.inspectFuncGetByID != nil {
		mmGetByID.mock.t.Fatalf("Inspect function is already set for OrderRepositoryMock.GetByID")
	}

	mmGetByID.mock.inspectFuncGetByID = f

	return mmGetByID
}

// Return sets up results that will be returned by OrderRepository.GetByID
func (mmGetByID *mOrderRepositoryMockGetByID) Return(op1 *domain.Order, err error) *OrderRepositoryMock {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("OrderRepositoryMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &OrderRepositoryMockGetByIDExpectation{mock: mmGetByID.mock}
	}
	mmGetByID.defaultExpectation.results = &OrderRepositoryMockGetByIDResults{op1, err}
	mmGetByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// Set uses given function f to mock the OrderRepository.GetByID method
func (mmGetByID *mOrderRepositoryMockGetByID) Set(f func(ctx context.Context, orderID int64) (op1 *domain.Order, err error)) *OrderRepositoryMock {
	if mmGetByID.defaultExpectation != nil {
		mmGetByID.mock.t.Fatalf("Default expectation is already set for the OrderRepository.GetByID method")
	}

	if len(mmGetByID.expectations) > 0 {
		mmGetByID.mock.t.Fatalf("Some expectations are already set for the OrderRepository.GetByID method")
	}

	mmGetByID.mock.funcGetByID = f
	mmGetByID.mock.funcGetByIDOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// When sets expectation for the OrderRepository.GetByID which will trigger the result defined by the following
// Then helper
func (mmGetByID *mOrderRepositoryMockGetByID) When(ctx context.Context, orderID int64) *OrderRepositoryMockGetByIDExpectation {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("OrderRepositoryMock.GetByID mock is already set by Set")
	}

	expectation := &OrderRepositoryMockGetByIDExpectation{
		mock:               mmGetByID.mock,
		params:             &OrderRepositoryMockGetByIDParams{ctx, orderID},
		expectationOrigins: OrderRepositoryMockGetByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByID.expectations = append(mmGetByID.expectations, expectation)
	return expectation
}

// Then sets up OrderRepository.GetByID return parameters for the expectation previously defined by the When method
func (e *OrderRepositoryMockGetByIDExpectation) Then(op1 *domain.Order, err error) *OrderRepositoryMock {
	e.results = &OrderRepositoryMockGetByIDResults{op1, err}
	return e.mock
}

// Times sets number of times OrderRepository.GetByID should be invoked
func (mmGetByID *mOrderRepositoryMockGetByID) Times(n uint64) *mOrderRepositoryMockGetByID {
	if n == 0 {
		mmGetByID.mock.t.Fatalf("Times of OrderRepositoryMock.GetByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByID.expectedInvocations, n)
	mmGetByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByID
}

func (mmGetByID *mOrderRepositoryMockGetByID) invocationsDone() bool {
	if len(mmGetByID.expectations) == 0 && mmGetByID.defaultExpectation == nil && mmGetByID.mock.funcGetByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByID.mock.afterGetByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByID implements mm_service.OrderRepository
func (mmGetByID *OrderRepositoryMock) GetByID(ctx context.Context, orderID int64) (op1 *domain.Order, err error) {
	mm_atomic.AddUint64(&mmGetByID.beforeGetByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByID.afterGetByIDCounter, 1)

	mmGetByID.t.Helper()

	if mmGetByID.inspectFuncGetByID != nil {
		mmGetByID.inspectFuncGetByID(ctx, orderID)
	}

	mm_params := OrderRepositoryMockGetByIDParams{ctx, orderID}

	// Record call args
	mmGetByID.GetByIDMock.mutex.Lock()
	mmGetByID.GetByIDMock.callArgs = append(mmGetByID.GetByIDMock.callArgs, &mm_params)
	mmGetByID.GetByIDMock.mutex.Unlock()

	for _, e := range mmGetByID.GetByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.op1, e.results.err
		}
	}

	if mmGetByID.GetByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByID.GetByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByID.GetByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByID.GetByIDMock.defaultExpectation.paramPtrs

		mm_got := OrderRepositoryMockGetByIDParams{ctx, orderID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByID.t.Errorf("OrderRepositoryMock.GetByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.orderID != nil && !minimock.Equal(*mm_want_ptrs.orderID, mm_got.orderID) {
				mmGetByID.t.Errorf("OrderRepositoryMock.GetByID got unexpected parameter orderID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originOrderID, *mm_want_ptrs.orderID, mm_got.orderID, minimock.Diff(*mm_want_ptrs.orderID, mm_got.orderID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByID.t.Errorf("OrderRepositoryMock.GetByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByID.GetByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByID.t.Fatal("No results are set for the OrderRepositoryMock.GetByID")
		}
		return (*mm_results).op1, (*mm_results).err
	}
	if mmGetByID.funcGetByID != nil {
		return mmGetByID.funcGetByID(ctx, orderID)
	}
	mmGetByID.t.Fatalf("Unexpected call to OrderRepositoryMock.GetByID. %v %v", ctx, orderID)
	return
}

// GetByIDAfterCounter returns a count of finished OrderRepositoryMock.GetByID invocations
func (mmGetByID *OrderRepositoryMock) GetByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.afterGetByIDCounter)
}

// GetByIDBeforeCounter returns a count of OrderRepositoryMock.GetByID invocations
func (mmGetByID *OrderRepositoryMock) GetByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.beforeGetByIDCounter)
}

// Calls returns a list of arguments used in each call to OrderRepositoryMock.GetByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByID *mOrderRepositoryMockGetByID) Calls() []*OrderRepositoryMockGetByIDParams {
	mmGetByID.mutex.RLock()

	argCopy := make([]*OrderRepositoryMockGetByIDParams, len(mmGetByID.callArgs))
	copy(argCopy, mmGetByID.callArgs)

	mmGetByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIDDone returns true if the count of the GetByID invocations corresponds
// the number of defined expectations
func (m *OrderRepositoryMock) MinimockGetByIDDone() bool {
	if m.GetByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIDMock.invocationsDone()
}

// MinimockGetByIDInspect logs each unmet expectation
func (m *OrderRepositoryMock) MinimockGetByIDInspect() {
	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderRepositoryMock.GetByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIDCounter := mm_atomic.LoadUint64(&m.afterGetByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIDMock.defaultExpectation != nil && afterGetByIDCounter < 1 {
		if m.GetByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OrderRepositoryMock.GetByID at\n%s", m.GetByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OrderRepositoryMock.GetByID at\n%s with params: %#v", m.GetByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByID != nil && afterGetByIDCounter < 1 {
		m.t.Errorf("Expected call to OrderRepositoryMock.GetByID at\n%s", m.funcGetByIDOrigin)
	}

	if !m.GetByIDMock.invocationsDone() && afterGetByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to OrderRepositoryMock.GetByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIDMock.expectedInvocations), m.GetByIDMock.expectedInvocationsOrigin, afterGetByIDCounter)
	}
}

type mOrderRepositoryMockInsert struct {
	optional           bool
	mock               *OrderRepositoryMock
	defaultExpectation *OrderRepositoryMockInsertExpectation
	expectations       []*OrderRepositoryMockInsertExpectation

	callArgs []*OrderRepositoryMockInsertParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OrderRepositoryMockInsertExpectation specifies expectation struct of the OrderRepository.Insert
type OrderRepositoryMockInsertExpectation struct {
	mock               *OrderRepositoryMock
	params             *OrderRepositoryMockInsertParams
	paramPtrs          *OrderRepositoryMockInsertParamPtrs
	expectationOrigins OrderRepositoryMockInsertExpectationOrigins
	results            *OrderRepositoryMockInsertResults
	returnOrigin       string
	Counter            uint64
}

// OrderRepositoryMockInsertParams contains parameters of the OrderRepository.Insert
type OrderRepositoryMockInsertParams struct {
	ctx   context.Context
	order *domain.Order
}

// OrderRepositoryMockInsertParamPtrs contains pointers to parameters of the OrderRepository.Insert
type OrderRepositoryMockInsertParamPtrs struct {
	ctx   *context.Context
	order **domain.Order
}

// OrderRepositoryMockInsertResults contains results of the OrderRepository.Insert
type OrderRepositoryMockInsertResults struct {
	i1  int64
	err error
}

// OrderRepositoryMockInsertOrigins contains origins of expectations of the OrderRepository.Insert
type OrderRepositoryMockInsertExpectationOrigins struct {
	origin      string
	originCtx   string
	originOrder string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInsert *mOrderRepositoryMockInsert) Optional() *mOrderRepositoryMockInsert {
	mmInsert.optional = true
	return mmInsert
}

// Expect sets up expected params for OrderRepository.Insert
func (mmInsert *mOrderRepositoryMockInsert) Expect(ctx context.Context, order *domain.Order) *mOrderRepositoryMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("OrderRepositoryMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &OrderRepositoryMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.paramPtrs != nil {
		mmInsert.mock.t.Fatalf("OrderRepositoryMock.Insert mock is already set by ExpectParams functions")
	}

	mmInsert.defaultExpectation.params = &OrderRepositoryMockInsertParams{ctx, order}
	mmInsert.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInsert.expectations {
		if minimock.Equal(e.params, mmInsert.defaultExpectation.params) {
			mmInsert.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInsert.defaultExpectation.params)
		}
	}

	return mmInsert
}

// ExpectCtxParam1 sets up expected param ctx for OrderRepository.Insert
func (mmInsert *mOrderRepositoryMockInsert) ExpectCtxParam1(ctx context.Context) *mOrderRepositoryMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("OrderRepositoryMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &OrderRepositoryMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.params != nil {
		mmInsert.mock.t.Fatalf("OrderRepositoryMock.Insert mock is already set by Expect")
	}

	if mmInsert.defaultExpectation.paramPtrs == nil {
		mmInsert.defaultExpectation.paramPtrs = &OrderRepositoryMockInsertParamPtrs{}
	}
	mmInsert.defaultExpectation.paramPtrs.ctx = &ctx
	mmInsert.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmInsert
}

// ExpectOrderParam2 sets up expected param order for OrderRepository.Insert
func (mmInsert *mOrderRepositoryMockInsert) ExpectOrderParam2(order *domain.Order) *mOrderRepositoryMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("OrderRepositoryMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &OrderRepositoryMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.params != nil {
		mmInsert.mock.t.Fatalf("OrderRepositoryMock.Insert mock is already set by Expect")
	}

	if mmInsert.defaultExpectation.paramPtrs == nil {
		mmInsert.defaultExpectation.paramPtrs = &OrderRepositoryMockInsertParamPtrs{}
	}
	mmInsert.defaultExpectation.paramPtrs.order = &order
	mmInsert.defaultExpectation.expectationOrigins.originOrder = minimock.CallerInfo(1)

	return mmInsert
}

// Inspect accepts an inspector function that has same arguments as the OrderRepository.Insert
func (mmInsert *mOrderRepositoryMockInsert) Inspect(f func(ctx context.Context, order *domain.Order)) *mOrderRepositoryMockInsert {
	if mmInsert.mock.inspectFuncInsert != nil {
		mmInsert.mock.t.Fatalf("Inspect function is already set for OrderRepositoryMock.Insert")
	}

	mmInsert.mock.inspectFuncInsert = f

	return mmInsert
}

// Return sets up results that will be returned by OrderRepository.Insert
func (mmInsert *mOrderRepositoryMockInsert) Return(i1 int64, err error) *OrderRepositoryMock {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("OrderRepositoryMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &OrderRepositoryMockInsertExpectation{mock: mmInsert.mock}
	}
	mmInsert.defaultExpectation.results = &OrderRepositoryMockInsertResults{i1, err}
	mmInsert.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInsert.mock
}

// Set uses given function f to mock the OrderRepository.Insert method
func (mmInsert *mOrderRepositoryMockInsert) Set(f func(ctx context.Context, order *domain.Order) (i1 int64, err error)) *OrderRepositoryMock {
	if mmInsert.defaultExpectation != nil {
		mmInsert.mock.t.Fatalf("Default expectation is already set for the OrderRepository.Insert method")
	}

	if len(mmInsert.expectations) > 0 {
		mmInsert.mock.t.Fatalf("Some expectations are already set for the OrderRepository.Insert method")
	}

	mmInsert.mock.funcInsert = f
	mmInsert.mock.funcInsertOrigin = minimock.CallerInfo(1)
	return mmInsert.mock
}

// When sets expectation for the OrderRepository.Insert which will trigger the result defined by the following
// Then helper
func (mmInsert *mOrderRepositoryMockInsert) When(ctx context.Context, order *domain.Order) *OrderRepositoryMockInsertExpectation {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("OrderRepositoryMock.Insert mock is already set by Set")
	}

	expectation := &OrderRepositoryMockInsertExpectation{
		mock:               mmInsert.mock,
		params:             &OrderRepositoryMockInsertParams{ctx, order},
		expectationOrigins: OrderRepositoryMockInsertExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInsert.expectations = append(mmInsert.expectations, expectation)
	return expectation
}

// Then sets up OrderRepository.Insert return parameters for the expectation previously defined by the When method
func (e *OrderRepositoryMockInsertExpectation) Then(i1 int64, err error) *OrderRepositoryMock {
	e.results = &OrderRepositoryMockInsertResults{i1, err}
	return e.mock
}

// Times sets number of times OrderRepository.Insert should be invoked
func (mmInsert *mOrderRepositoryMockInsert) Times(n uint64) *mOrderRepositoryMockInsert {
	if n == 0 {
		mmInsert.mock.t.Fatalf("Times of OrderRepositoryMock.Insert mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInsert.expectedInvocations, n)
	mmInsert.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInsert
}

func (mmInsert *mOrderRepositoryMockInsert) invocationsDone() bool {
	if len(mmInsert.expectations) == 0 && mmInsert.defaultExpectation == nil && mmInsert.mock.funcInsert == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInsert.mock.afterInsertCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInsert.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Insert implements mm_service.OrderRepository
func (mmInsert *OrderRepositoryMock) Insert(ctx context.Context, order *domain.Order) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmInsert.beforeInsertCounter, 1)
	defer mm_atomic.AddUint64(&mmInsert.afterInsertCounter, 1)

	mmInsert.t.Helper()

	if mmInsert.inspectFuncInsert != nil {
		mmInsert.inspectFuncInsert(ctx, order)
	}

	mm_params := OrderRepositoryMockInsertParams{ctx, order}

	// Record call args
	mmInsert.InsertMock.mutex.Lock()
	mmInsert.InsertMock.callArgs = append(mmInsert.InsertMock.callArgs, &mm_params)
	mmInsert.InsertMock.mutex.Unlock()

	for _, e := range mmInsert.InsertMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmInsert.InsertMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInsert.InsertMock.defaultExpectation.Counter, 1)
		mm_want := mmInsert.InsertMock.defaultExpectation.params
		mm_want_ptrs := mmInsert.InsertMock.defaultExpectation.paramPtrs

		mm_got := OrderRepositoryMockInsertParams{ctx, order}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmInsert.t.Errorf("OrderRepositoryMock.Insert got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsert.InsertMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.order != nil && !minimock.Equal(*mm_want_ptrs.order, mm_got.order) {
				mmInsert.t.Errorf("OrderRepositoryMock.Insert got unexpected parameter order, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsert.InsertMock.defaultExpectation.expectationOrigins.originOrder, *mm_want_ptrs.order, mm_got.order, minimock.Diff(*mm_want_ptrs.order, mm_got.order))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInsert.t.Errorf("OrderRepositoryMock.Insert got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInsert.InsertMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmInsert.InsertMock.defaultExpectation.results
		if mm_results == nil {
			mmInsert.t.Fatal("No results are set for the OrderRepositoryMock.Insert")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmInsert.funcInsert != nil {
		return mmInsert.funcInsert(ctx, order)
	}
	mmInsert.t.Fatalf("Unexpected call to OrderRepositoryMock.Insert. %v %v", ctx, order)
	return
}

// InsertAfterCounter returns a count of finished OrderRepositoryMock.Insert invocations
func (mmInsert *OrderRepositoryMock) InsertAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInsert.afterInsertCounter)
}

// InsertBeforeCounter returns a count of OrderRepositoryMock.Insert invocations
func (mmInsert *OrderRepositoryMock) InsertBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInsert.beforeInsertCounter)
}

// Calls returns a list of arguments used in each call to OrderRepositoryMock.Insert.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInsert *mOrderRepositoryMockInsert) Calls() []*OrderRepositoryMockInsertParams {
	mmInsert.mutex.RLock()

	argCopy := make([]*OrderRepositoryMockInsertParams, len(mmInsert.callArgs))
	copy(argCopy, mmInsert.callArgs)

	mmInsert.mutex.RUnlock()

	return argCopy
}

// MinimockInsertDone returns true if the count of the Insert invocations corresponds
// the number of defined expectations
func (m *OrderRepositoryMock) MinimockInsertDone() bool {
	if m.InsertMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InsertMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InsertMock.invocationsDone()
}

// MinimockInsertInspect logs each unmet expectation
func (m *OrderRepositoryMock) MinimockInsertInspect() {
	for _, e := range m.InsertMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderRepositoryMock.Insert at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInsertCounter := mm_atomic.LoadUint64(&m.afterInsertCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InsertMock.defaultExpectation != nil && afterInsertCounter < 1 {
		if m.InsertMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OrderRepositoryMock.Insert at\n%s", m.InsertMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OrderRepositoryMock.Insert at\n%s with params: %#v", m.InsertMock.defaultExpectation.expectationOrigins.origin, *m.InsertMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInsert != nil && afterInsertCounter < 1 {
		m.t.Errorf("Expected call to OrderRepositoryMock.Insert at\n%s", m.funcInsertOrigin)
	}

	if !m.InsertMock.invocationsDone() && afterInsertCounter > 0 {
		m.t.Errorf("Expected %d calls to OrderRepositoryMock.Insert at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InsertMock.expectedInvocations), m.InsertMock.expectedInvocationsOrigin, afterInsertCounter)
	}
}

type mOrderRepositoryMockUpdateStatus struct {
	optional           bool
	mock               *OrderRepositoryMock
	defaultExpectation *OrderRepositoryMockUpdateStatusExpectation
	expectations       []*OrderRepositoryMockUpdateStatusExpectation

	callArgs []*OrderRepositoryMockUpdateStatusParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OrderRepositoryMockUpdateStatusExpectation specifies expectation struct of the OrderRepository.UpdateStatus
type OrderRepositoryMockUpdateStatusExpectation struct {
	mock               *OrderRepositoryMock
	params             *OrderRepositoryMockUpdateStatusParams
	paramPtrs          *OrderRepositoryMockUpdateStatusParamPtrs
	expectationOrigins OrderRepositoryMockUpdateStatusExpectationOrigins
	results            *OrderRepositoryMockUpdateStatusResults
	returnOrigin       string
	Counter            uint64
}

// OrderRepositoryMockUpdateStatusParams contains parameters of the OrderRepository.UpdateStatus
type OrderRepositoryMockUpdateStatusParams struct {
	ctx       context.Context
	orderID   int64
	newStatus domain.Status
}

// OrderRepositoryMockUpdateStatusParamPtrs contains pointers to parameters of the OrderRepository.UpdateStatus
type OrderRepositoryMockUpdateStatusParamPtrs struct {
	ctx       *context.Context
	orderID   *int64
	newStatus *domain.Status
}

// OrderRepositoryMockUpdateStatusResults contains results of the OrderRepository.UpdateStatus
type OrderRepositoryMockUpdateStatusResults struct {
	err error
}

// OrderRepositoryMockUpdateStatusOrigins contains origins of expectations of the OrderRepository.UpdateStatus
type OrderRepositoryMockUpdateStatusExpectationOrigins struct {
	origin          string
	originCtx       string
	originOrderID   string
	originNewStatus string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateStatus *mOrderRepositoryMockUpdateStatus) Optional() *mOrderRepositoryMockUpdateStatus {
	mmUpdateStatus.optional = true
	return mmUpdateStatus
}

// Expect sets up expected params for OrderRepository.UpdateStatus
func (mmUpdateStatus *mOrderRepositoryMockUpdateStatus) Expect(ctx context.Context, orderID int64, newStatus domain.Status) *mOrderRepositoryMockUpdateStatus {
	if mmUpdateStatus.mock.funcUpdateStatus != nil {
		mmUpdateStatus.mock.t.Fatalf("OrderRepositoryMock.UpdateStatus mock is already set by Set")
	}

	if mmUpdateStatus.defaultExpectation == nil {
		mmUpdateStatus.defaultExpectation = &OrderRepositoryMockUpdateStatusExpectation{}
	}

	if mmUpdateStatus.defaultExpectation.paramPtrs != nil {
		mmUpdateStatus.mock.t.Fatalf("OrderRepositoryMock.UpdateStatus mock is already set by ExpectParams functions")
	}

	mmUpdateStatus.defaultExpectation.params = &OrderRepositoryMockUpdateStatusParams{ctx, orderID, newStatus}
	mmUpdateStatus.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateStatus.expectations {
		if minimock.Equal(e.params, mmUpdateStatus.defaultExpectation.params) {
			mmUpdateStatus.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateStatus.defaultExpectation.params)
		}
	}

	return mmUpdateStatus
}

// ExpectCtxParam1 sets up expected param ctx for OrderRepository.UpdateStatus
func (mmUpdateStatus *mOrderRepositoryMockUpdateStatus) ExpectCtxParam1(ctx context.Context) *mOrderRepositoryMockUpdateStatus {
	if mmUpdateStatus.mock.funcUpdateStatus != nil {
		mmUpdateStatus.mock.t.Fatalf("OrderRepositoryMock.UpdateStatus mock is already set by Set")
	}

	if mmUpdateStatus.defaultExpectation == nil {
		mmUpdateStatus.defaultExpectation = &OrderRepositoryMockUpdateStatusExpectation{}
	}

	if mmUpdateStatus.defaultExpectation.params != nil {
		mmUpdateStatus.mock.t.Fatalf("OrderRepositoryMock.UpdateStatus mock is already set by Expect")
	}

	if mmUpdateStatus.defaultExpectation.paramPtrs == nil {
		mmUpdateStatus.defaultExpectation.paramPtrs = &OrderRepositoryMockUpdateStatusParamPtrs{}
	}
	mmUpdateStatus.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdateStatus.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdateStatus
}

// ExpectOrderIDParam2 sets up expected param orderID for OrderRepository.UpdateStatus
func (mmUpdateStatus *mOrderRepositoryMockUpdateStatus) ExpectOrderIDParam2(orderID int64) *mOrderRepositoryMockUpdateStatus {
	if mmUpdateStatus.mock.funcUpdateStatus != nil {
		mmUpdateStatus.mock.t.Fatalf("OrderRepositoryMock.UpdateStatus mock is already set by Set")
	}

	if mmUpdateStatus.defaultExpectation == nil {
		mmUpdateStatus.defaultExpectation = &OrderRepositoryMockUpdateStatusExpectation{}
	}

	if mmUpdateStatus.defaultExpectation.params != nil {
		mmUpdateStatus.mock.t.Fatalf("OrderRepositoryMock.UpdateStatus mock is already set by Expect")
	}

	if mmUpdateStatus.defaultExpectation.paramPtrs == nil {
		mmUpdateStatus.defaultExpectation.paramPtrs = &OrderRepositoryMockUpdateStatusParamPtrs{}
	}
	mmUpdateStatus.defaultExpectation.paramPtrs.orderID = &orderID
	mmUpdateStatus.defaultExpectation.expectationOrigins.originOrderID = minimock.CallerInfo(1)

	return mmUpdateStatus
}

// ExpectNewStatusParam3 sets up expected param newStatus for OrderRepository.UpdateStatus
func (mmUpdateStatus *mOrderRepositoryMockUpdateStatus) ExpectNewStatusParam3(newStatus domain.Status) *mOrderRepositoryMockUpdateStatus {
	if mmUpdateStatus.mock.funcUpdateStatus != nil {
		mmUpdateStatus.mock.t.Fatalf("OrderRepositoryMock.UpdateStatus mock is already set by Set")
	}

	if mmUpdateStatus.defaultExpectation == nil {
		mmUpdateStatus.defaultExpectation = &OrderRepositoryMockUpdateStatusExpectation{}
	}

	if mmUpdateStatus.defaultExpectation.params != nil {
		mmUpdateStatus.mock.t.Fatalf("OrderRepositoryMock.UpdateStatus mock is already set by Expect")
	}

	if mmUpdateStatus.defaultExpectation.paramPtrs == nil {
		mmUpdateStatus.defaultExpectation.paramPtrs = &OrderRepositoryMockUpdateStatusParamPtrs{}
	}
	mmUpdateStatus.defaultExpectation.paramPtrs.newStatus = &newStatus
	mmUpdateStatus.defaultExpectation.expectationOrigins.originNewStatus = minimock.CallerInfo(1)

	return mmUpdateStatus
}

// Inspect accepts an inspector function that has same arguments as the OrderRepository.UpdateStatus
func (mmUpdateStatus *mOrderRepositoryMockUpdateStatus) Inspect(f func(ctx context.Context, orderID int64, newStatus domain.Status)) *mOrderRepositoryMockUpdateStatus {
	if mmUpdateStatus.mock.inspectFuncUpdateStatus != nil {
		mmUpdateStatus.mock.t.Fatalf("Inspect function is already set for OrderRepositoryMock.UpdateStatus")
	}

	mmUpdateStatus.mock.inspectFuncUpdateStatus = f

	return mmUpdateStatus
}

// Return sets up results that will be returned by OrderRepository.UpdateStatus
func (mmUpdateStatus *mOrderRepositoryMockUpdateStatus) Return(err error) *OrderRepositoryMock {
	if mmUpdateStatus.mock.funcUpdateStatus != nil {
		mmUpdateStatus.mock.t.Fatalf("OrderRepositoryMock.UpdateStatus mock is already set by Set")
	}

	if mmUpdateStatus.defaultExpectation == nil {
		mmUpdateStatus.defaultExpectation = &OrderRepositoryMockUpdateStatusExpectation{mock: mmUpdateStatus.mock}
	}
	mmUpdateStatus.defaultExpectation.results = &OrderRepositoryMockUpdateStatusResults{err}
	mmUpdateStatus.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateStatus.mock
}

// Set uses given function f to mock the OrderRepository.UpdateStatus method
func (mmUpdateStatus *mOrderRepositoryMockUpdateStatus) Set(f func(ctx context.Context, orderID int64, newStatus domain.Status) (err error)) *OrderRepositoryMock {
	if mmUpdateStatus.defaultExpectation != nil {
		mmUpdateStatus.mock.t.Fatalf("Default expectation is already set for the OrderRepository.UpdateStatus method")
	}

	if len(mmUpdateStatus.expectations) > 0 {
		mmUpdateStatus.mock.t.Fatalf("Some expectations are already set for the OrderRepository.UpdateStatus method")
	}

	mmUpdateStatus.mock.funcUpdateStatus = f
	mmUpdateStatus.mock.funcUpdateStatusOrigin = minimock.CallerInfo(1)
	return mmUpdateStatus.mock
}

// When sets expectation for the OrderRepository.UpdateStatus which will trigger the result defined by the following
// Then helper
func (mmUpdateStatus *mOrderRepositoryMockUpdateStatus) When(ctx context.Context, orderID int64, newStatus domain.Status) *OrderRepositoryMockUpdateStatusExpectation {
	if mmUpdateStatus.mock.funcUpdateStatus != nil {
		mmUpdateStatus.mock.t.Fatalf("OrderRepositoryMock.UpdateStatus mock is already set by Set")
	}

	expectation := &OrderRepositoryMockUpdateStatusExpectation{
		mock:               mmUpdateStatus.mock,
		params:             &OrderRepositoryMockUpdateStatusParams{ctx, orderID, newStatus},
		expectationOrigins: OrderRepositoryMockUpdateStatusExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateStatus.expectations = append(mmUpdateStatus.expectations, expectation)
	return expectation
}

// Then sets up OrderRepository.UpdateStatus return parameters for the expectation previously defined by the When method
func (e *OrderRepositoryMockUpdateStatusExpectation) Then(err error) *OrderRepositoryMock {
	e.results = &OrderRepositoryMockUpdateStatusResults{err}
	return e.mock
}

// Times sets number of times OrderRepository.UpdateStatus should be invoked
func (mmUpdateStatus *mOrderRepositoryMockUpdateStatus) Times(n uint64) *mOrderRepositoryMockUpdateStatus {
	if n == 0 {
		mmUpdateStatus.mock.t.Fatalf("Times of OrderRepositoryMock.UpdateStatus mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateStatus.expectedInvocations, n)
	mmUpdateStatus.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateStatus
}

func (mmUpdateStatus *mOrderRepositoryMockUpdateStatus) invocationsDone() bool {
	if len(mmUpdateStatus.expectations) == 0 && mmUpdateStatus.defaultExpectation == nil && mmUpdateStatus.mock.funcUpdateStatus == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateStatus.mock.afterUpdateStatusCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateStatus.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateStatus implements mm_service.OrderRepository
func (mmUpdateStatus *OrderRepositoryMock) UpdateStatus(ctx context.Context, orderID int64, newStatus domain.Status) (err error) {
	mm_atomic.AddUint64(&mmUpdateStatus.beforeUpdateStatusCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateStatus.afterUpdateStatusCounter, 1)

	mmUpdateStatus.t.Helper()

	if mmUpdateStatus.inspectFuncUpdateStatus != nil {
		mmUpdateStatus.inspectFuncUpdateStatus(ctx, orderID, newStatus)
	}

	mm_params := OrderRepositoryMockUpdateStatusParams{ctx, orderID, newStatus}

	// Record call args
	mmUpdateStatus.UpdateStatusMock.mutex.Lock()
	mmUpdateStatus.UpdateStatusMock.callArgs = append(mmUpdateStatus.UpdateStatusMock.callArgs, &mm_params)
	mmUpdateStatus.UpdateStatusMock.mutex.Unlock()

	for _, e := range mmUpdateStatus.UpdateStatusMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdateStatus.UpdateStatusMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateStatus.UpdateStatusMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateStatus.UpdateStatusMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateStatus.UpdateStatusMock.defaultExpectation.paramPtrs

		mm_got := OrderRepositoryMockUpdateStatusParams{ctx, orderID, newStatus}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdateStatus.t.Errorf("OrderRepositoryMock.UpdateStatus got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateStatus.UpdateStatusMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.orderID != nil && !minimock.Equal(*mm_want_ptrs.orderID, mm_got.orderID) {
				mmUpdateStatus.t.Errorf("OrderRepositoryMock.UpdateStatus got unexpected parameter orderID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateStatus.UpdateStatusMock.defaultExpectation.expectationOrigins.originOrderID, *mm_want_ptrs.orderID, mm_got.orderID, minimock.Diff(*mm_want_ptrs.orderID, mm_got.orderID))
			}

			if mm_want_ptrs.newStatus != nil && !minimock.Equal(*mm_want_ptrs.newStatus, mm_got.newStatus) {
				mmUpdateStatus.t.Errorf("OrderRepositoryMock.UpdateStatus got unexpected parameter newStatus, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateStatus.UpdateStatusMock.defaultExpectation.expectationOrigins.originNewStatus, *mm_want_ptrs.newStatus, mm_got.newStatus, minimock.Diff(*mm_want_ptrs.newStatus, mm_got.newStatus))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateStatus.t.Errorf("OrderRepositoryMock.UpdateStatus got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateStatus.UpdateStatusMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateStatus.UpdateStatusMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateStatus.t.Fatal("No results are set for the OrderRepositoryMock.UpdateStatus")
		}
		return (*mm_results).err
	}
	if mmUpdateStatus.funcUpdateStatus != nil {
		return mmUpdateStatus.funcUpdateStatus(ctx, orderID, newStatus)
	}
	mmUpdateStatus.t.Fatalf("Unexpected call to OrderRepositoryMock.UpdateStatus. %v %v %v", ctx, orderID, newStatus)
	return
}

// UpdateStatusAfterCounter returns a count of finished OrderRepositoryMock.UpdateStatus invocations
func (mmUpdateStatus *OrderRepositoryMock) UpdateStatusAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateStatus.afterUpdateStatusCounter)
}

// UpdateStatusBeforeCounter returns a count of OrderRepositoryMock.UpdateStatus invocations
func (mmUpdateStatus *OrderRepositoryMock) UpdateStatusBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateStatus.beforeUpdateStatusCounter)
}

// Calls returns a list of arguments used in each call to OrderRepositoryMock.UpdateStatus.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateStatus *mOrderRepositoryMockUpdateStatus) Calls() []*OrderRepositoryMockUpdateStatusParams {
	mmUpdateStatus.mutex.RLock()

	argCopy := make([]*OrderRepositoryMockUpdateStatusParams, len(mmUpdateStatus.callArgs))
	copy(argCopy, mmUpdateStatus.callArgs)

	mmUpdateStatus.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateStatusDone returns true if the count of the UpdateStatus invocations corresponds
// the number of defined expectations
func (m *OrderRepositoryMock) MinimockUpdateStatusDone() bool {
	if m.UpdateStatusMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateStatusMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateStatusMock.invocationsDone()
}

// MinimockUpdateStatusInspect logs each unmet expectation
func (m *OrderRepositoryMock) MinimockUpdateStatusInspect() {
	for _, e := range m.UpdateStatusMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OrderRepositoryMock.UpdateStatus at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateStatusCounter := mm_atomic.LoadUint64(&m.afterUpdateStatusCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateStatusMock.defaultExpectation != nil && afterUpdateStatusCounter < 1 {
		if m.UpdateStatusMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OrderRepositoryMock.UpdateStatus at\n%s", m.UpdateStatusMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OrderRepositoryMock.UpdateStatus at\n%s with params: %#v", m.UpdateStatusMock.defaultExpectation.expectationOrigins.origin, *m.UpdateStatusMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateStatus != nil && afterUpdateStatusCounter < 1 {
		m.t.Errorf("Expected call to OrderRepositoryMock.UpdateStatus at\n%s", m.funcUpdateStatusOrigin)
	}

	if !m.UpdateStatusMock.invocationsDone() && afterUpdateStatusCounter > 0 {
		m.t.Errorf("Expected %d calls to OrderRepositoryMock.UpdateStatus at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateStatusMock.expectedInvocations), m.UpdateStatusMock.expectedInvocationsOrigin, afterUpdateStatusCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OrderRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetByIDInspect()

			m.MinimockInsertInspect()

			m.MinimockUpdateStatusInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OrderRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OrderRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetByIDDone() &&
		m.MinimockInsertDone() &&
		m.MinimockUpdateStatusDone()
}
