// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i route256/cart/internal/service.LomsService -o loms_service_mock.go -n LomsServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// LomsServiceMock implements mm_service.LomsService
type LomsServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetStockInfo          func(ctx context.Context, skuID int64) (u1 uint32, err error)
	funcGetStockInfoOrigin    string
	inspectFuncGetStockInfo   func(ctx context.Context, skuID int64)
	afterGetStockInfoCounter  uint64
	beforeGetStockInfoCounter uint64
	GetStockInfoMock          mLomsServiceMockGetStockInfo
}

// NewLomsServiceMock returns a mock for mm_service.LomsService
func NewLomsServiceMock(t minimock.Tester) *LomsServiceMock {
	m := &LomsServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetStockInfoMock = mLomsServiceMockGetStockInfo{mock: m}
	m.GetStockInfoMock.callArgs = []*LomsServiceMockGetStockInfoParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLomsServiceMockGetStockInfo struct {
	optional           bool
	mock               *LomsServiceMock
	defaultExpectation *LomsServiceMockGetStockInfoExpectation
	expectations       []*LomsServiceMockGetStockInfoExpectation

	callArgs []*LomsServiceMockGetStockInfoParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsServiceMockGetStockInfoExpectation specifies expectation struct of the LomsService.GetStockInfo
type LomsServiceMockGetStockInfoExpectation struct {
	mock               *LomsServiceMock
	params             *LomsServiceMockGetStockInfoParams
	paramPtrs          *LomsServiceMockGetStockInfoParamPtrs
	expectationOrigins LomsServiceMockGetStockInfoExpectationOrigins
	results            *LomsServiceMockGetStockInfoResults
	returnOrigin       string
	Counter            uint64
}

// LomsServiceMockGetStockInfoParams contains parameters of the LomsService.GetStockInfo
type LomsServiceMockGetStockInfoParams struct {
	ctx   context.Context
	skuID int64
}

// LomsServiceMockGetStockInfoParamPtrs contains pointers to parameters of the LomsService.GetStockInfo
type LomsServiceMockGetStockInfoParamPtrs struct {
	ctx   *context.Context
	skuID *int64
}

// LomsServiceMockGetStockInfoResults contains results of the LomsService.GetStockInfo
type LomsServiceMockGetStockInfoResults struct {
	u1  uint32
	err error
}

// LomsServiceMockGetStockInfoOrigins contains origins of expectations of the LomsService.GetStockInfo
type LomsServiceMockGetStockInfoExpectationOrigins struct {
	origin      string
	originCtx   string
	originSkuID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetStockInfo *mLomsServiceMockGetStockInfo) Optional() *mLomsServiceMockGetStockInfo {
	mmGetStockInfo.optional = true
	return mmGetStockInfo
}

// Expect sets up expected params for LomsService.GetStockInfo
func (mmGetStockInfo *mLomsServiceMockGetStockInfo) Expect(ctx context.Context, skuID int64) *mLomsServiceMockGetStockInfo {
	if mmGetStockInfo.mock.funcGetStockInfo != nil {
		mmGetStockInfo.mock.t.Fatalf("LomsServiceMock.GetStockInfo mock is already set by Set")
	}

	if mmGetStockInfo.defaultExpectation == nil {
		mmGetStockInfo.defaultExpectation = &LomsServiceMockGetStockInfoExpectation{}
	}

	if mmGetStockInfo.defaultExpectation.paramPtrs != nil {
		mmGetStockInfo.mock.t.Fatalf("LomsServiceMock.GetStockInfo mock is already set by ExpectParams functions")
	}

	mmGetStockInfo.defaultExpectation.params = &LomsServiceMockGetStockInfoParams{ctx, skuID}
	mmGetStockInfo.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetStockInfo.expectations {
		if minimock.Equal(e.params, mmGetStockInfo.defaultExpectation.params) {
			mmGetStockInfo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetStockInfo.defaultExpectation.params)
		}
	}

	return mmGetStockInfo
}

// ExpectCtxParam1 sets up expected param ctx for LomsService.GetStockInfo
func (mmGetStockInfo *mLomsServiceMockGetStockInfo) ExpectCtxParam1(ctx context.Context) *mLomsServiceMockGetStockInfo {
	if mmGetStockInfo.mock.funcGetStockInfo != nil {
		mmGetStockInfo.mock.t.Fatalf("LomsServiceMock.GetStockInfo mock is already set by Set")
	}

	if mmGetStockInfo.defaultExpectation == nil {
		mmGetStockInfo.defaultExpectation = &LomsServiceMockGetStockInfoExpectation{}
	}

	if mmGetStockInfo.defaultExpectation.params != nil {
		mmGetStockInfo.mock.t.Fatalf("LomsServiceMock.GetStockInfo mock is already set by Expect")
	}

	if mmGetStockInfo.defaultExpectation.paramPtrs == nil {
		mmGetStockInfo.defaultExpectation.paramPtrs = &LomsServiceMockGetStockInfoParamPtrs{}
	}
	mmGetStockInfo.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetStockInfo.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetStockInfo
}

// ExpectSkuIDParam2 sets up expected param skuID for LomsService.GetStockInfo
func (mmGetStockInfo *mLomsServiceMockGetStockInfo) ExpectSkuIDParam2(skuID int64) *mLomsServiceMockGetStockInfo {
	if mmGetStockInfo.mock.funcGetStockInfo != nil {
		mmGetStockInfo.mock.t.Fatalf("LomsServiceMock.GetStockInfo mock is already set by Set")
	}

	if mmGetStockInfo.defaultExpectation == nil {
		mmGetStockInfo.defaultExpectation = &LomsServiceMockGetStockInfoExpectation{}
	}

	if mmGetStockInfo.defaultExpectation.params != nil {
		mmGetStockInfo.mock.t.Fatalf("LomsServiceMock.GetStockInfo mock is already set by Expect")
	}

	if mmGetStockInfo.defaultExpectation.paramPtrs == nil {
		mmGetStockInfo.defaultExpectation.paramPtrs = &LomsServiceMockGetStockInfoParamPtrs{}
	}
	mmGetStockInfo.defaultExpectation.paramPtrs.skuID = &skuID
	mmGetStockInfo.defaultExpectation.expectationOrigins.originSkuID = minimock.CallerInfo(1)

	return mmGetStockInfo
}

// Inspect accepts an inspector function that has same arguments as the LomsService.GetStockInfo
func (mmGetStockInfo *mLomsServiceMockGetStockInfo) Inspect(f func(ctx context.Context, skuID int64)) *mLomsServiceMockGetStockInfo {
	if mmGetStockInfo.mock.inspectFuncGetStockInfo != nil {
		mmGetStockInfo.mock.t.Fatalf("Inspect function is already set for LomsServiceMock.GetStockInfo")
	}

	mmGetStockInfo.mock.inspectFuncGetStockInfo = f

	return mmGetStockInfo
}

// Return sets up results that will be returned by LomsService.GetStockInfo
func (mmGetStockInfo *mLomsServiceMockGetStockInfo) Return(u1 uint32, err error) *LomsServiceMock {
	if mmGetStockInfo.mock.funcGetStockInfo != nil {
		mmGetStockInfo.mock.t.Fatalf("LomsServiceMock.GetStockInfo mock is already set by Set")
	}

	if mmGetStockInfo.defaultExpectation == nil {
		mmGetStockInfo.defaultExpectation = &LomsServiceMockGetStockInfoExpectation{mock: mmGetStockInfo.mock}
	}
	mmGetStockInfo.defaultExpectation.results = &LomsServiceMockGetStockInfoResults{u1, err}
	mmGetStockInfo.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetStockInfo.mock
}

// Set uses given function f to mock the LomsService.GetStockInfo method
func (mmGetStockInfo *mLomsServiceMockGetStockInfo) Set(f func(ctx context.Context, skuID int64) (u1 uint32, err error)) *LomsServiceMock {
	if mmGetStockInfo.defaultExpectation != nil {
		mmGetStockInfo.mock.t.Fatalf("Default expectation is already set for the LomsService.GetStockInfo method")
	}

	if len(mmGetStockInfo.expectations) > 0 {
		mmGetStockInfo.mock.t.Fatalf("Some expectations are already set for the LomsService.GetStockInfo method")
	}

	mmGetStockInfo.mock.funcGetStockInfo = f
	mmGetStockInfo.mock.funcGetStockInfoOrigin = minimock.CallerInfo(1)
	return mmGetStockInfo.mock
}

// When sets expectation for the LomsService.GetStockInfo which will trigger the result defined by the following
// Then helper
func (mmGetStockInfo *mLomsServiceMockGetStockInfo) When(ctx context.Context, skuID int64) *LomsServiceMockGetStockInfoExpectation {
	if mmGetStockInfo.mock.funcGetStockInfo != nil {
		mmGetStockInfo.mock.t.Fatalf("LomsServiceMock.GetStockInfo mock is already set by Set")
	}

	expectation := &LomsServiceMockGetStockInfoExpectation{
		mock:               mmGetStockInfo.mock,
		params:             &LomsServiceMockGetStockInfoParams{ctx, skuID},
		expectationOrigins: LomsServiceMockGetStockInfoExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetStockInfo.expectations = append(mmGetStockInfo.expectations, expectation)
	return expectation
}

// Then sets up LomsService.GetStockInfo return parameters for the expectation previously defined by the When method
func (e *LomsServiceMockGetStockInfoExpectation) Then(u1 uint32, err error) *LomsServiceMock {
	e.results = &LomsServiceMockGetStockInfoResults{u1, err}
	return e.mock
}

// Times sets number of times LomsService.GetStockInfo should be invoked
func (mmGetStockInfo *mLomsServiceMockGetStockInfo) Times(n uint64) *mLomsServiceMockGetStockInfo {
	if n == 0 {
		mmGetStockInfo.mock.t.Fatalf("Times of LomsServiceMock.GetStockInfo mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetStockInfo.expectedInvocations, n)
	mmGetStockInfo.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetStockInfo
}

func (mmGetStockInfo *mLomsServiceMockGetStockInfo) invocationsDone() bool {
	if len(mmGetStockInfo.expectations) == 0 && mmGetStockInfo.defaultExpectation == nil && mmGetStockInfo.mock.funcGetStockInfo == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetStockInfo.mock.afterGetStockInfoCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetStockInfo.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetStockInfo implements mm_service.LomsService
func (mmGetStockInfo *LomsServiceMock) GetStockInfo(ctx context.Context, skuID int64) (u1 uint32, err error) {
	mm_atomic.AddUint64(&mmGetStockInfo.beforeGetStockInfoCounter, 1)
	defer mm_atomic.AddUint64(&mmGetStockInfo.afterGetStockInfoCounter, 1)

	mmGetStockInfo.t.Helper()

	if mmGetStockInfo.inspectFuncGetStockInfo != nil {
		mmGetStockInfo.inspectFuncGetStockInfo(ctx, skuID)
	}

	mm_params := LomsServiceMockGetStockInfoParams{ctx, skuID}

	// Record call args
	mmGetStockInfo.GetStockInfoMock.mutex.Lock()
	mmGetStockInfo.GetStockInfoMock.callArgs = append(mmGetStockInfo.GetStockInfoMock.callArgs, &mm_params)
	mmGetStockInfo.GetStockInfoMock.mutex.Unlock()

	for _, e := range mmGetStockInfo.GetStockInfoMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmGetStockInfo.GetStockInfoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetStockInfo.GetStockInfoMock.defaultExpectation.Counter, 1)
		mm_want := mmGetStockInfo.GetStockInfoMock.defaultExpectation.params
		mm_want_ptrs := mmGetStockInfo.GetStockInfoMock.defaultExpectation.paramPtrs

		mm_got := LomsServiceMockGetStockInfoParams{ctx, skuID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetStockInfo.t.Errorf("LomsServiceMock.GetStockInfo got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetStockInfo.GetStockInfoMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.skuID != nil && !minimock.Equal(*mm_want_ptrs.skuID, mm_got.skuID) {
				mmGetStockInfo.t.Errorf("LomsServiceMock.GetStockInfo got unexpected parameter skuID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetStockInfo.GetStockInfoMock.defaultExpectation.expectationOrigins.originSkuID, *mm_want_ptrs.skuID, mm_got.skuID, minimock.Diff(*mm_want_ptrs.skuID, mm_got.skuID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetStockInfo.t.Errorf("LomsServiceMock.GetStockInfo got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetStockInfo.GetStockInfoMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetStockInfo.GetStockInfoMock.defaultExpectation.results
		if mm_results == nil {
			mmGetStockInfo.t.Fatal("No results are set for the LomsServiceMock.GetStockInfo")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmGetStockInfo.funcGetStockInfo != nil {
		return mmGetStockInfo.funcGetStockInfo(ctx, skuID)
	}
	mmGetStockInfo.t.Fatalf("Unexpected call to LomsServiceMock.GetStockInfo. %v %v", ctx, skuID)
	return
}

// GetStockInfoAfterCounter returns a count of finished LomsServiceMock.GetStockInfo invocations
func (mmGetStockInfo *LomsServiceMock) GetStockInfoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStockInfo.afterGetStockInfoCounter)
}

// GetStockInfoBeforeCounter returns a count of LomsServiceMock.GetStockInfo invocations
func (mmGetStockInfo *LomsServiceMock) GetStockInfoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStockInfo.beforeGetStockInfoCounter)
}

// Calls returns a list of arguments used in each call to LomsServiceMock.GetStockInfo.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetStockInfo *mLomsServiceMockGetStockInfo) Calls() []*LomsServiceMockGetStockInfoParams {
	mmGetStockInfo.mutex.RLock()

	argCopy := make([]*LomsServiceMockGetStockInfoParams, len(mmGetStockInfo.callArgs))
	copy(argCopy, mmGetStockInfo.callArgs)

	mmGetStockInfo.mutex.RUnlock()

	return argCopy
}

// MinimockGetStockInfoDone returns true if the count of the GetStockInfo invocations corresponds
// the number of defined expectations
func (m *LomsServiceMock) MinimockGetStockInfoDone() bool {
	if m.GetStockInfoMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetStockInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetStockInfoMock.invocationsDone()
}

// MinimockGetStockInfoInspect logs each unmet expectation
func (m *LomsServiceMock) MinimockGetStockInfoInspect() {
	for _, e := range m.GetStockInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsServiceMock.GetStockInfo at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetStockInfoCounter := mm_atomic.LoadUint64(&m.afterGetStockInfoCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetStockInfoMock.defaultExpectation != nil && afterGetStockInfoCounter < 1 {
		if m.GetStockInfoMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsServiceMock.GetStockInfo at\n%s", m.GetStockInfoMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsServiceMock.GetStockInfo at\n%s with params: %#v", m.GetStockInfoMock.defaultExpectation.expectationOrigins.origin, *m.GetStockInfoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetStockInfo != nil && afterGetStockInfoCounter < 1 {
		m.t.Errorf("Expected call to LomsServiceMock.GetStockInfo at\n%s", m.funcGetStockInfoOrigin)
	}

	if !m.GetStockInfoMock.invocationsDone() && afterGetStockInfoCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsServiceMock.GetStockInfo at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetStockInfoMock.expectedInvocations), m.GetStockInfoMock.expectedInvocationsOrigin, afterGetStockInfoCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LomsServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetStockInfoInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LomsServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LomsServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetStockInfoDone()
}
